version: 2.1

workflows:
  tests:
    jobs:
      - test_package

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.7
    resource_class: medium

commands:
  setup_environment:
    steps:
      - run:
          name: "Install virtualenv, python 3.7 and required packages"
          command: |
            python -m virtualenv .env
            source .env/bin/activate
            pip install --upgrade pip
            pip install .[test]
jobs:
  test_package:
    executor: docker-executor
    steps:
      - checkout
      - setup_environment
      - run:
          name: "Test khmer-nltk functionalities"
          command: |
            source .env/bin/activate
            pytest tests